### PR TITLE
added the totp option to the docker entrypoint to enable usage of tot…

### PR DESCRIPTION
**Pull request by sideisra**
…p secured user accounts with docker.

### CODE REVIEW

**Comment by klg71** [comment]
Hey @sideisra tanks for your pull request :) I will try to release it as soon as possible :)

**Comment by klg71** [comment]
Released with version 0.2.50: https://hub.docker.com/r/klg71/keycloakmigration/tags Please confirm :)

**Comment by sideisra** [comment]
Nope there is a problem. I get: ./entrypoint.sh: line 12: syntax error: unexpected end of file (expecting "fi"). Looking into it...

**Comment by sideisra** [comment]
Found it. The handling of the default value for ADMIN_TOTP was wrong. Here is the fix: #69. Sorry for the regression.

**Comment by klg71** [comment]
Ok can you try version 0.2.51? :)

**Pull request merged**
